Merge UserCollection into Master
bookbrainz/bookbrainz-site pull request #505
Opened 2020-09-01 09:36 UTC by prabalsingh24

### Problem
Merge UserCollection into Master

2020-09-01 15:32 UTC, MonkeyDo requested changes
I see a couple of merge issues, but nothing dramatic.
After that, it's ready to merge ! 🎉 🚀

2020-09-01 15:32 UTC, MonkeyDo commented on package.json
> +    "bluebird": "^3.5.1",
The need for the bluebird library has been removed in a previous PR, and we shouldn't need the package anymore.

2020-09-01 15:32 UTC, MonkeyDo commented on src/server/helpers/middleware.js
> +import Promise from 'bluebird';
Same comment as on package.json, bluebird has been removed and this line shouldn't be needed.

2020-09-01 15:32 UTC, MonkeyDo commented on src/client/helpers/setupIconLibrary.js
> +	faPlus, faQuestionCircle, faRemoveFormat, faSave, faSearch, faSignInAlt,
It looks like these lines were duplicated during the merge from master.
You'll need to make sure the result does have the 3 new icons in there (faComment, faGripVertical and faSave)

2020-09-05 11:53 UTC, prabalsingh24 commented
Coverage decreased (-1.7%), that's sad. I was hoping it to be increased. But I think because we don't have tests for front end stuff, and alot of front end code was added, it decreased.

2020-09-07 16:23 UTC, MonkeyDo approved these changes
Let's go !

2020-09-07 16:24 UTC, merged