Fixed responsiveness of buttons in create-collection page
bookbrainz/bookbrainz-site pull request #527
Opened 2020-10-27 18:27 UTC by frappelatte28

### Problem
https://tickets.metabrainz.org/browse/BB-558
![WhatsApp Image 2020-10-27 at 2 27 13 PM](https://user-images.githubusercontent.com/64382399/97345330-d21e9700-1881-11eb-9e10-b3992df1aaf2.jpeg)

### Solution
![Screenshot from 2020-10-27 18-12-44](https://user-images.githubusercontent.com/64382399/97344161-4ce6b280-1880-11eb-8e55-3d374826aabd.png)

Applied top margin for mobile screens using media query.

### Areas of Impact

src/client/components/forms/userCollection.js
src/client/stylesheets/style.less

2020-10-27 18:28 UTC, frappelatte28 commented
@MonkeyDo Please  kindly review this PR :)

2020-10-28 13:17 UTC, MonkeyDo reviewed
Thanks, good find!

I have a suggestion for a different approach:
First of all, let's fix the issue with the overlapping buttons in a way that will fix it across the website. I've identified the issue is coming from the bootstrap theme, but can (and has) been mitigated; see this bit of CSS used previously to sort the issue of horizontal overlap:
https://github.com/bookbrainz/bookbrainz-site/blob/master/src/client/stylesheets/style.less#L83-L87
I propose to change that simply to `margin: 0;` to fix the overlapping issue vertically as well.

With that out of the way, I think there is a simple way to display our buttons properly using existing css.
We can use bootstrap's responsive grid system by modifying the structure just a bit:
```html
<div class="row">
  <div class="col-sm-6">
    <button type="button" class="btn btn-block btn-primary">Add another collaborator</button>
  </div>
  <div class="col-sm-6">
    <button type="submit" class="btn btn-block btn-success">Create collection</button>
  </div>
</div>
```

1. We change the `text-center` class of the parent element to `row`
2. We create two `<div class="col-sm-6">` elements around the existing buttons
3. Profit.

I think it looks quite good like that, with full width buttons in mobile sizes, and better looking as well in desktop sizes I find:

![Capture d’écran 2020-10-28 à 14 23 52](https://user-images.githubusercontent.com/6179856/97441726-50824400-1929-11eb-9d3f-2a1f1ca274db.png)
![Capture d’écran 2020-10-28 à 14 23 35](https://user-images.githubusercontent.com/6179856/97441673-43655500-1929-11eb-9731-c7e2c24a0cfe.png)



How does that sound?

2020-11-03 13:53 UTC, frappelatte28 commented
@MonkeyDo 
i think we can achieve the same with little less mess ,
we can use predefined " no-gutters " class on .row to remove negative margin of row and extra gutters of columns .

https://getbootstrap.com/docs/4.0/layout/grid/#no-gutters


also , i think giving space between two buttons will look more nicer so i think we can use above "no-gutter" method and then add the space manually in this section .

what do you think?

2020-11-05 20:34 UTC, MonkeyDo commented
> on .row to remove negative margin of row and extra gutters of columns

I'm not sure I understand your suggestion. Which .row element do you want to modify?
I don't follow how it will solve the issue.

We're using an older version of Bootstrap that doesn't have the `no-gutter` class, but that's not a huge issue as we can always define some css class for it.

2020-11-08 15:10 UTC, frappelatte28 commented
> We're using an older version of Bootstrap that doesn't have the `no-gutter` class, but that's not a huge issue as we can always define some css class for it.

yes i agree on this .

also 
i have tested this code 
```
<div class="row">
  <div class="col-sm-6">
    <button type="button" class="btn btn-block btn-primary">Add another collaborator</button>
  </div>
  <div class="col-sm-6">
    <button type="submit" class="btn btn-block btn-success">Create collection</button>
  </div>
</div>
```

looks great to me , 
i should make a commit using this !

2020-11-08 16:56 UTC, frappelatte28 commented
@MonkeyDo  please review the changes !

2020-11-09 13:58 UTC, MonkeyDo requested changes
It's looking quite good !
A suggestion below to simplify the fix.

Also, currently our continuous integration (CI) [tests are failing](https://travis-ci.org/github/bookbrainz/bookbrainz-site/jobs/742261082#L701) on simple code style issues, which you can easily fix by running this command: `npm run lint -- --fix` before committing the changes to the `userCollection.js` file.

2020-11-09 13:58 UTC, MonkeyDo commented on src/client/components/forms/userCollection.js
> +								<div className = "col-sm-6">
You can add a simple Bootstrap class to add a space on top of both of these `col-sm-6` elements, which will give a bit of space between the buttons when they are on top of each other:

```suggestion
								<div className = "col-sm-6 margin-top-d5">
```

With that simply change on both elements, you can remove the changes to the `style.less` file.

2020-11-09 13:58 UTC, MonkeyDo commented on src/client/stylesheets/style.less
> +	.buttons-container > button:nth-child(2) {
This `buttons-container` class is not used anywhere, so this code block is unused, and can be removed.

As mentioned in the comment above, we can add a bit of space between the buttons using existing bootstrap classes instead.

2020-11-10 11:21 UTC, frappelatte28 commented
@MonkeyDo Please review the changes!

2020-11-10 14:54 UTC, MonkeyDo reviewed
Just two more details and I think this will be perfect :)

2020-11-10 14:54 UTC, MonkeyDo commented on src/client/components/forms/userCollection.js
> +									<Button
```suggestion
									<Button
										block
```

This makes the button take up all the available space, which I think looks quite nice:

Before:
<img width="418" alt="Capture d’écran 2020-11-10 à 15 51 10" src="https://user-images.githubusercontent.com/6179856/98689838-9a791a00-236c-11eb-82a9-a56f29ee8edf.png">


After:
<img width="367" alt="Capture d’écran 2020-11-10 à 15 43 48" src="https://user-images.githubusercontent.com/6179856/98689728-7ddce200-236c-11eb-84d7-219de18231a3.png">

2020-11-10 14:54 UTC, MonkeyDo commented on src/client/components/forms/userCollection.js
> +									<Button
```suggestion
									<Button
										block
```

Same as above.

2020-11-10 14:54 UTC, MonkeyDo commented on src/client/components/forms/userCollection.js
> +							<div className="row">
```suggestion
							<div className="row margin-bottom-2">
```

This makes sure there's a bit of space between the buttons and the footer.

2020-11-10 15:09 UTC, MonkeyDo commented on src/client/components/forms/userCollection.js
>  										<Button
I just noticed the third button ("Delete"), which is only visible when you edit one of your own collections.

It should receive the same changes as the other buttons, meaning it should also be wrapped in a `<div>` in the same way and the button should have the `block` attribute.

Here's the full block of code:

```jsx
{
	this.props.collection.id ?
		<div className="col-sm-6 margin-top-d5">
			<Button
				block
				bsStyle="danger"
				type="button"
				onClick={this.handleShowModal}
			>
				<FontAwesomeIcon icon="trash-alt"/>&nbsp;Delete collection
			</Button>
		</div> : null
}
```

With three buttons in mind, it's worth you having another pass to see if it looks good with the three buttons.

2020-11-18 16:49 UTC, frappelatte28 commented
@MonkeyDo  Sorry for the late commit, I was occupied with some work, I have made the requested changes, feel free to let me know if you need any further changes.

2020-11-24 18:20 UTC, MonkeyDo approved these changes
Thank you for your PR, this now looks  a whole lot better !
:rocket:

2020-11-24 18:20 UTC, merged